name: Deploy site to GitHub Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Deploy site to GitHub Pages
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'hoXyy'
        reponame: 'bingo-sheet-file-generator'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
